#The Mysql only stores the wonderful player Data
Use-Mysql: false
#Only edit this area if Use-Mysql = true
Host: 127.0.0.1
Port: 3306
User: 'root'
Password: 'Your_Password_Goes_Here_1234'
Database: 'MCBitCoin'
